name: visloc_apr
channels:
  - owlas
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit
  - python=3.7
  - pytorch
  - torchvision
  - visdom
  - jupyter
  - matplotlib
  - transforms3d

